from .index import index_bp
from .login import login_bp
from .register import register_bp
from .admin import admin_bp
from .logout import logout_bp
from .profile import profile_bp
from .courses import course_bp
from .endpoint import endpoint_bp
from .forgot_password import forgot_pass_bp
